MPI_FLAGS = -DUSE_MPI -I$(MPI_HOME)/include

NVCC		= nvcc 
#-ccbin /opt/cray/xt-asyncpe/5.17/bin/CC
FLAGS		= -arch=sm_35
DFLAGS	= $(MPI_FLAGS) -lineinfo
RFLAGS 	= $(MPI_FLAGS) -O3 -DNDEBUG 

#SILO_INCLUDES := /usr/local/silo-4.8/include
#SILO_LIBS := /usr/local/silo-4.8/lib

LINKFLAGS = -L$(MPI_HOME)/lib -lmpi
#LINKFLAGS += -L$(SILO_LIBS) -lsilo

#INC_SILO:= -I$(SILO_INCLUDES)

#ASYNC
MP_INCLUDE= -I$(PREFIX)/include
MP_LIB= -L$(PREFIX)/lib -lmp -lgdsync -lgdrapi -lcuda -libverbs 


all: release 

debug: LINKFLAGS += 

release: 	FLAGS += $(RFLAGS)
debug: 		FLAGS += $(DFLAGS)

release: lulesh
debug: lulesh

lulesh: allocator.o lulesh.o lulesh-comms.o lulesh-comms-gpu.o comm.o
	$(NVCC) -o lulesh allocator.o lulesh.o lulesh-comms.o lulesh-comms-gpu.o comm.o $(LINKFLAGS) $(MP_LIB)
#$(FLAGS) $(MP_INCLUDE) 
allocator.o: allocator.cu vector.h
	$(NVCC) $(FLAGS) allocator.cu -I ./ -c -o allocator.o

comm.o: comm.cc comm.h
	mpic++ $(MP_INCLUDE) $(MPI_FLAGS) comm.cc -c $< -o $@

lulesh.o: lulesh.cu util.h vector.h allocator.h
	$(NVCC) $(FLAGS) lulesh.cu -I ./ $(MP_INCLUDE) $(INC_SILO) -c -o lulesh.o

lulesh-comms.o: lulesh-comms.cu
	$(NVCC) $(FLAGS) lulesh-comms.cu -I./ $(MP_INCLUDE) -c -o lulesh-comms.o

lulesh-comms-gpu.o: lulesh-comms-gpu.cu
	$(NVCC) $(FLAGS) lulesh-comms-gpu.cu -I./ -c -o lulesh-comms-gpu.o

clean: 
	rm -rf allocator.o comm.o lulesh-comms.o lulesh-comms-gpu.o lulesh.o lulesh xyz.asc regNumList.txt
